# Generated by Django 5.2.4 on 2025-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID чата Telegram",
                max_length=50,
                null=True,
                verbose_name="ID чата Telegram",
            ),
        ),
    ]
