# Generated by Django 5.2.4 on 2025-08-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.TextField(blank=True, help_text="Укажите действие", null=True, verbose_name="Действие"),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Привычка является приятной",
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Введите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "приятная привычка",
                "verbose_name_plural": "приятные привычки",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.TextField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время выполнения привычки",
                        null=True,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.TextField(blank=True, help_text="Укажите действие", null=True, verbose_name="Действие"),
                ),
                (
                    "periodic",
                    models.DateTimeField(
                        blank=True, help_text="Укажите периодичность привычки", null=True, verbose_name="Периодичность"
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение привычки",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите время на выполнение привычки",
                        null=True,
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Опубликовать привычку",
                        null=True,
                        verbose_name="Признак публичности привычки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Введите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите приятную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.pleasanthabit",
                        verbose_name="Приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
