# Generated by Django 5.2.4 on 2025-08-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="periodic",
        ),
    ]
