# Generated by Django 5.2.4 on 2025-08-20 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_periodic"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1, message="Периодичность не может быть меньше 1 дня"),
                    django.core.validators.MaxValueValidator(7, message="Периодичность не может быть больше 7 дней"),
                ],
                verbose_name="Периодичность (дни)",
            ),
        ),
    ]
