# Generated by Django 5.2.4 on 2025-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pleasanthabit",
            name="is_pleasant",
            field=models.BooleanField(
                default=True, help_text="Привычка является приятной", verbose_name="Признак приятной привычки"
            ),
        ),
    ]
